In [31]:
import numpy as np

## Exercise 1

In [21]:
## We want to perform the multiplication update of C=AB+C when given A,B,C matrices
def ijk(C, A, B):
    for i in range(0,n):
        for j in range(0,n):
            for k in range(0,n):
                C[i,j] = A[i,k]*B[k,j]+ C[i,j]
    return C

## np.dot gives the inner product of two vectors, so we give the functions the corresponding rows/columns
def ijk_improved(A,B,C):
    for i in range(0,n):
        for j in range(0,n):
            C[i,j]= np.dot(A[i,:], B[:,j])+C[i,j]
    return C


def ijk_improved2(A,B,C):
    for i in range(0,n):
        for k in range(0,n):
            aux=A[i,k] ## only one memory access
            for j in range(0,n):
                C[i,j]= aux*B[k,j]+C[i,j]
    return C
        

In [22]:
A = np.array([[1,2], [1,2]])
B = np.array([[3,2], [6,2]])
C = np.array([[8,2], [4,3]])
n = 2
ijk(C, A, B)

array([[23,  8],
       [19,  9]])

In [25]:
## We want to perform the multiplication update of C=AB+C when given A,B,C matrices
def ijk(C, A, B):
    C = np.matmul(A,B) + C
    # C = A @ B + C
    return C

A = np.array([[1,2], [1,2]])
B = np.array([[3,2], [6,2]])
C = np.array([[8,2], [4,3]])
ijk(C, A, B)

array([[23,  8],
       [19,  9]])

In [15]:
A = np.array([[1,2], [1,2]])


array([[1, 4],
       [1, 4]])

In [3]:
A=np.matrix('1,2,3;1,0,2;1,1,0')
B=np.matrix('1,2,0; 2,2,1; 1,1,0')
C=np.zeros((3,3))

In [4]:
n=3
C=np.zeros((3,3))
ijk(A,B, C)

matrix([[1, 2, 3],
        [1, 0, 2],
        [1, 1, 0]])

In [5]:
C=np.zeros((3,3))
ijk_improved(A,B,C)

array([[8., 9., 2.],
       [3., 4., 0.],
       [3., 4., 1.]])

In [6]:
C=np.zeros((3,3))
ijk_improved2(A,B,C)

array([[8., 9., 2.],
       [3., 4., 0.],
       [3., 4., 1.]])

In [7]:
#D=np.random.matrix(n)

## Exercise 2

In [8]:
## Consider n=Nb the dimension of the matrices 

def blockmatprod(A,B):
    C=np.zeros((n,n))
    for i in range(0,N):
        for j in range(0,N): #we load block C[i,j] into fast memory
            for k in range(0,N):
                for ii in range(i*b, (i+1)*b): ## we are moving inside the smaller blocks
                    for jj in range(j*b, (j+1)*b):
                        for kk in range(k*b, (k+1)*b):
                            C[ii, jj] = A[ii, kk]*B[kk, jj] + C[ii,jj]
    return C


In [9]:
N=3
n=N*N
b=3
A=np.random.rand(n,n)
B=np.random.rand(n,n)
blockmatprod(A,B)

array([[2.49898851, 2.33335071, 2.74979888, 1.86850881, 1.63943249,
        2.7233057 , 1.86215575, 2.13911531, 1.84245012],
       [2.66882736, 2.03932786, 2.20340207, 1.72957515, 1.78476291,
        2.63362451, 2.15806848, 2.00019158, 1.53502047],
       [2.59004929, 2.41162934, 2.62591867, 2.05284553, 2.4514991 ,
        2.50582127, 2.27329996, 3.07980751, 2.45330893],
       [2.63343076, 2.25025402, 2.62350681, 1.9741416 , 2.18957729,
        2.0765548 , 1.65377711, 2.37977785, 2.36564665],
       [2.69967483, 2.6763627 , 2.63251779, 1.58898207, 2.77782046,
        2.27923551, 2.08943909, 2.33869051, 1.81332426],
       [1.74122737, 1.37832085, 1.72536816, 1.45081452, 1.32266214,
        1.82508475, 1.00919126, 2.25236281, 1.74684728],
       [1.58464348, 1.26592622, 1.6854438 , 1.1357861 , 1.11218022,
        1.56929102, 1.48920814, 1.27373567, 1.12947787],
       [2.29162182, 2.30806796, 2.47130437, 1.40660384, 1.91435999,
        2.32538051, 1.68751466, 1.86304553, 1.44531407],


## Exercise 3

Remember how to do the LU=A factorization. Given the matrix \begin{pmatrix} 2 & 3 \\ 1 & 7 \end{pmatrix} we need to diagonalize to get the upper matrix \begin{pmatrix} 2 & 3 \\ 0 & 7-2/3 \end{pmatrix} then \begin{pmatrix} 1 & 0 \\ 1/2 & 1 \end{pmatrix}
We apply the LU factorization for each matrix block of the global matrix A =LU:\begin{pmatrix} A_{11} & A_{12} \\ A_{21} & A_{22} \end{pmatrix} Then we get the factorization given by the block matrices 
\begin{equation*}
A= LU= \begin{pmatrix} I & 0 \\ L & I \end{pmatrix}\begin{pmatrix} U_{11} & U_{12} \\ 0 & U_{22} \end{pmatrix}
\end{equation*}

We are seeking to write a block-partioned LU algorithm. The procedure should be based on:
\begin{equation*}
A= LU= \begin{pmatrix} L_{11} & 0 \\ L_{21} & I \end{pmatrix} \begin{pmatrix} I & 0 \\ 0 & S \end{pmatrix} \begin{pmatrix} U_{11} & U_{12} \\ 0 & I \end{pmatrix}= \begin{pmatrix} L_{11} U_{11} & L_{11} U_{12} \\ L_{21} U_{11} & L_{21} U_{12}+S \end{pmatrix}
\end{equation*}
where $S=A_{22}-L_{21}U_{12}$ is the Schur complement of $A_{11}$, therefore $A_{22}=L_{21} U_{12}+S$ is given in the las step of the algorithm using the multiplication update. 

In [42]:
## LU algorithm has already been implemented
#from scipy.linalg import lu

import scipy.linalg

In [34]:
## LU factorization:
def lunopiv(A, n, ptol):
    for k in range(0,n-1):
        pivot= A[k,k]
        if abs(pivot) < ptol:    ## we need the pivot to be positive in order to diagonalize the matrix
            print('zero pivot encountered')
            break
        for i in range(k+1, n):
            A[i,k] = A[i,k]/pivot 
            for j in range(k+1, n):
                A[i,j] = A[i,j] - A[i,k]*A[k,j]
        L= np.eye(n)+np.tril(A,-1)
        U= np.triu(A)
        return L, U

In [39]:
A = np.array([[1,1], [1,2]])
Lprova, Uprova = lunopiv(A, 2, 1.e-16)
Lprova

array([[1., 0.],
       [1., 1.]])

In [40]:
Uprova

array([[1, 1],
       [0, 1]])

Note that we can directly import a function that already executes the diagonalization PLU. 

In [46]:
from scipy.linalg import lu

P, Lprova2, Uprova2 = lu(A)
Lprova2

array([[1., 0.],
       [1., 1.]])

We already have the first step of the algorithm, just applying the LU factorization to each block of the total matrix. \
For the second step, we need to solve many linear systems un order to find $U_{12}$. \
Now we have a new set of linear systems for the third step, however we have to modify the initial expression$L_{21} U_{11} = A_{21} \iff (L_{21} U_{11})^T = A_{21}^T$. 

Solutions: http://www.maia.ub.es/~vieiro/docencia/NLA/pr1/

In [50]:
n =6
A=np.zeros((n,n))
for i in range(0,n):
    for j in range(0,n):
        A[i,j] = np.random.normal(0,10)
        
LU=np.zeros((n,n))
r=3
nblocks= int(n/r)
Aij=np.zeros((nblocks, nblocks), np.matrix)
S=np.copy(A)

for i in range(0,nblocks-1):
    Aij[0,0] = np.copy(S[0:r, 0:r])
    Aij[0,1] = np.copy(S[0:r, r:n])
    Aij[1,0] = np.copy(S[r:n, 0:r])
    Aij[1,1] = np.copy(S[r:n, r:n])
    L11, U11 = lunopiv(Aij[0,0], r, 1.e-16)
    
    print('%d %24.16e\n' % (i, np.linalg.norm(np.dot(L11, U11) - S[0:r, 0:r], np.inf)))
    
    U12 = np.linalg.solve(L11, Aij[0,1])    ## step 2
    L21t= np.linalg.solve(U11.T, Aij[1,0].T) ##step 3
    
    ## np.solve is equivalent to GEPP
    
    LU[i*r:(i+1)*r, i*r:(i+1)*r] = np.copy(np.tril(L11, -1) + U11)
    LU[i*r: (i+1)*r, (i+1)*r:n] = np.copy(U12)
    LU[(i+1)*r:n, i*r: (i+1)*r] = np.copy(L21t.T)
    
    S= Aij[1,1]-np.dot(L21t.T, U12)
    
Aij[0,0]=S[0:r, 0:r]
L11, U11 = lunopiv(Aij[0,0] , r, 1.e-16)
LU[n-r:n, n-r: n] = np.copy(np.tril(L11, -1) + U11)

print('LU factorization (r = %d) \n' %(r))
#for i in range(0,n):
#    for j in range(0,n):
 
LU

0   2.1535579681777730e+02

LU factorization (r = 3) 



array([[-2.25121934e+00, -5.51702407e+00,  6.48838847e-01,
         3.58582524e+00, -1.06454678e+01,  1.07127723e+01],
       [ 9.85758251e-02,  3.47964287e+00, -8.00779975e+00,
        -1.48890108e+01, -1.65073987e+01,  3.40939700e+00],
       [ 2.44546358e+00,  2.05346341e+01, -6.58141025e+00,
         3.06808169e+02,  3.78549558e+02, -1.04921850e+02],
       [-4.59965044e+00, -6.54446187e+00,  7.25017010e+00,
        -2.30046485e+03, -2.90888024e+03,  8.25896537e+02],
       [ 2.40721134e+00,  8.45768577e+00, -1.19241564e+01,
        -1.63947490e+00, -8.48833716e+01,  5.41411352e+01],
       [-6.63035606e+00, -1.61554303e+01,  1.83025389e+01,
         2.54118584e+00,  1.36877093e+02, -6.59075313e+01]])