## Algorithms for symmetric, banded and sparse matrices

We have a symmetric matrix. By definition a banded matrix is a matrix which has elements on the middle diagonals and zeros on the upper and lower part of the matrix. A sparse system consists of a matrix that has many zeros. \
\
For symmetric matrices the factorization consists of $A = LDL^T$, where $D$ is diagonal. When the matrix is in addition positive definite, then we can define $D^{1/2}$ and then find $G= L D^{1/2}$, such that $A= GG^T$, which is called the Cholesky factorization. \
\
Note that some pivoting strategies do not preserve the structure of the matrices, for instance some of them do not preserve the trace, which is a really important problem. 

### Banded systems

In [1]:
import numpy as np
import scipy.linalg as spla

#### Problem 1:

In [2]:
def isBanded(A, p, q, tol, n):
    ## p rows with zero elements bellow the diagonal (lower bandwidth)
    ## q rows with zero elements above the diagonal  (upper bandwidth)
    for i in range(0,n):
        for j in range(0,max(-p+i, 0)):
            if abs(A[i,j]) > tol:
                return 0
        for j in range(min(i+q+1, n), n):
            if abs(A[i,j]) > tol:
                return 0
    return 1

## if it is banded returns 1 !!

In [3]:
def checkBanded(A, tol, n):
    #up, down= -1,-1
    for p in range(0,n):
        for q in range(0,n):
            #print(p, q, isBanded(A, p, q, tol, n))
            if isBanded(A, p, q, tol, n) == 1:
                return np.array([p,q])
            ## finish this program to check the boundaries

If we have a huge matrix we need to work with smaller arrays. Note that for every kind of system there are speecific functions



We denote a banded matrix in terms of the lower bandwidth, p, and the upper bandwidth, q, which represents the number of rows bellow the diagonal and columns above the diagonal, respectively, that are different to zero. In general, we don't include the diagonal itself (1st row/column).

In [4]:
import random
def randomMatrix(dim):
    A = np.zeros((dim,dim))
    for i in range(0, dim):
        for j in range(0,dim):
            A[i,j] = random.uniform(0,1)
    return A

In [5]:
def bandedMatrix(dim, p, q):
    A= np.zeros((dim,dim))
    for i in range(0, dim):
        for j in range(max(-p+i, 0), min(i+q+1, dim)):
            A[i,j] = random.uniform(0,1)
    return A

In [6]:
A=bandedMatrix(4, 2, 1)
print(A)
isAbanded = isBanded(A, 2, 1, 0.001, 4)
print(isAbanded)
isAbanded2 = isBanded(A, 2, 2, 0.0001, 4)
print(isAbanded2)
isAbanded3 = isBanded(A, 1, 1, 0.0001, 4)
print(isAbanded3)
parameters = checkBanded(A, 0.0001,4)
print(parameters)
## The minimum p,q for which it is banded are the real banded parameters

[[0.35953753 0.78467279 0.         0.        ]
 [0.51755114 0.28343952 0.4797608  0.        ]
 [0.44973161 0.69786839 0.81546    0.40477566]
 [0.         0.41102438 0.92615855 0.25137618]]
1
1
0
[2 1]


In [7]:
A=randomMatrix(4)
print(A)

[[0.95780447 0.44319061 0.12236616 0.23022172]
 [0.57300514 0.95965399 0.67478832 0.96486115]
 [0.57942318 0.72935912 0.87426255 0.05553082]
 [0.87809761 0.6763801  0.5330076  0.62364101]]


We wish to compute now the LU and PLU factorization of banded matrices:

In [8]:
## LU factorization:
def lunopiv(A, n, ptol):
    for k in range(0,n-1):
        pivot= A[k,k]
        if abs(pivot) < ptol:    ## we need the pivot to be positive in order to diagonalize the matrix
            print('zero pivot encountered')
            break
        for i in range(k+1, n):
            A[i,k] = A[i,k]/pivot 
            for j in range(k+1, n):
                A[i,j] = A[i,j] - A[i,k]*A[k,j]
        L= np.eye(n)+np.tril(A,-1)
        U= np.triu(A)
        return L, U


In [9]:
from scipy.linalg import lu

In [10]:
## LU factorization for different banded matrices
A= bandedMatrix(4, 2, 1)
B = bandedMatrix(4,1,1)
C = bandedMatrix(4, 2, 2)

print(A)
print(B)
print(C)

[[0.92184639 0.41688692 0.         0.        ]
 [0.35613916 0.32694999 0.33856549 0.        ]
 [0.89242185 0.70557773 0.81664079 0.74745045]
 [0.         0.76667487 0.59463946 0.52141777]]
[[0.74672253 0.19327604 0.         0.        ]
 [0.69427437 0.21813876 0.27365385 0.        ]
 [0.         0.31017291 0.10036968 0.04308792]
 [0.         0.         0.23248406 0.96050782]]
[[0.74318699 0.32085708 0.16351161 0.        ]
 [0.07119707 0.79105432 0.08730218 0.95100875]
 [0.45076001 0.27800629 0.80318512 0.26334644]
 [0.         0.84094289 0.42543409 0.46022902]]


In [11]:
La, Ua = lunopiv(A, 4, 1.e-16)
Lb, Ub = lunopiv(B, 4, 1.e-16)
Lc, Uc = lunopiv(C, 4, 1.e-16)

print('LU factorization of banded matrices \n')
print(La)
print(Ua)
print(Lb)
print(Ub)
print(Lc)
print(Uc)

LU factorization of banded matrices 

[[1.         0.         0.         0.        ]
 [0.38633244 1.         0.         0.        ]
 [0.96808086 0.30199748 1.         0.        ]
 [0.         0.76667487 0.59463946 1.        ]]
[[0.92184639 0.41688692 0.         0.        ]
 [0.         0.16589305 0.33856549 0.        ]
 [0.         0.         0.81664079 0.74745045]
 [0.         0.         0.         0.52141777]]
[[1.         0.         0.         0.        ]
 [0.92976217 1.         0.         0.        ]
 [0.         0.31017291 1.         0.        ]
 [0.         0.         0.23248406 1.        ]]
[[0.74672253 0.19327604 0.         0.        ]
 [0.         0.03843801 0.27365385 0.        ]
 [0.         0.         0.10036968 0.04308792]
 [0.         0.         0.         0.96050782]]
[[1.         0.         0.         0.        ]
 [0.09579967 1.         0.         0.        ]
 [0.60652301 0.08339909 1.         0.        ]
 [0.         0.84094289 0.42543409 1.        ]]
[[0.74318699 0.32

The LU diagonalization of banded matrices gives us L matrices lower triangular and U upper triangular with diagonals different of zero given by the parameters p and q respectively

In [12]:
PA, LA, UA = lu(A)
PB, LB, UB = lu(B)
PC, LC, UC = lu(C)

print('PLU factorization of banded matrices \n')

print(PA)
print(LA)
print(UA)
print(PB)
print(LB)
print(UB)
print(PC)
print(LC)
print(UC)

PLU factorization of banded matrices 

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
[[1.         0.         0.         0.        ]
 [0.         1.         0.         0.        ]
 [0.9522411  0.16866668 1.         0.        ]
 [0.39907042 0.05918388 0.02565653 1.        ]]
[[ 0.96808086  0.30199748  0.81664079  0.74745045]
 [ 0.          0.76667487  0.59463946  0.52141777]
 [ 0.          0.         -0.87793479 -0.79969885]
 [ 0.          0.          0.         -0.30862739]]
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]
[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.80313284  0.52359574  1.          0.        ]
 [ 0.          0.         -0.85367404  1.        ]]
[[ 0.92976217  0.03843801  0.27365385  0.        ]
 [ 0.          0.31017291  0.10036968  0.04308792]
 [ 0.          0.         -0.27233353 -0.02256065]
 [ 0.          0.          0.          0.94124837]]
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 

In [13]:
print(A)
print(La+Ua)

[[0.92184639 0.41688692 0.         0.        ]
 [0.38633244 0.16589305 0.33856549 0.        ]
 [0.96808086 0.30199748 0.81664079 0.74745045]
 [0.         0.76667487 0.59463946 0.52141777]]
[[1.92184639 0.41688692 0.         0.        ]
 [0.38633244 1.16589305 0.33856549 0.        ]
 [0.96808086 0.30199748 1.81664079 0.74745045]
 [0.         0.76667487 0.59463946 1.52141777]]


In [14]:
print(LA + UA)

[[ 1.96808086  0.30199748  0.81664079  0.74745045]
 [ 0.          1.76667487  0.59463946  0.52141777]
 [ 0.9522411   0.16866668  0.12206521 -0.79969885]
 [ 0.39907042  0.05918388  0.02565653  0.69137261]]


In [ ]:
## Now the same with the scipy lpu factorization!!!

#### Problem 2: Multiplication of banded matrices

Let's consider now the multiplication of banded matrices in order to create a function that stores C= AB by diagonals

In [15]:
def ijk_improved(A,B,C):
    for i in range(0,n):
        for j in range(0,n):
            C[i,j]= np.dot(A[i,:], B[:,j])+C[i,j]
    return C


def ijk_improved2(A,B,C):
    for i in range(0,n):
        for k in range(0,n):
            aux=A[i,k] ## only one memory access
            for j in range(0,n):
                C[i,j]= aux*B[k,j]+C[i,j]
    return C
        

In [16]:
print(A)
print(B)

[[0.92184639 0.41688692 0.         0.        ]
 [0.38633244 0.16589305 0.33856549 0.        ]
 [0.96808086 0.30199748 0.81664079 0.74745045]
 [0.         0.76667487 0.59463946 0.52141777]]
[[0.74672253 0.19327604 0.         0.        ]
 [0.92976217 0.03843801 0.27365385 0.        ]
 [0.         0.31017291 0.10036968 0.04308792]
 [0.         0.         0.23248406 0.96050782]]


In [17]:
n=4
D=np.zeros((n,n))
D=ijk_improved2(A,B,D)
print(D)

[[1.07596916 0.19419512 0.11408271 0.        ]
 [0.44272422 0.18605924 0.07937898 0.01458808]
 [1.00367363 0.45201487 0.33837907 0.75311936]
 [0.7128253  0.21391051 0.39070863 0.52644762]]


Note that multiplying A(2,1) and B(1,1) we get a matrix D(3,2). So the bandwidth add each other. Let's study the transposed:

In [18]:
n=4
D=np.zeros((n,n))
D=ijk_improved2(B,A,D)
print(D)

[[0.76303228 0.34336201 0.0654366  0.        ]
 [1.1368668  0.47662506 0.23649068 0.20454269]
 [0.21699583 0.11480135 0.2126016  0.09748818]
 [0.22506337 0.80660681 0.76101182 0.67459616]]


In [19]:
n=4
D=np.zeros((n,n))
D=ijk_improved2(B,C,D)
print(D)

[[0.57347026 0.38654214 0.13594368 0.18380721]
 [0.86064686 0.3503683  0.347436   0.10862065]
 [0.09059099 0.28043475 0.1112126  0.34123946]
 [0.14100693 0.82712118 0.57230424 0.50327742]]


Here we multiply B(1,1) and C(2,2) getting a matrix D(3,3) which is not banded at all, since we are in dimension 4. Similarly:

In [20]:
n=4
D=np.zeros((n,n))
D=ijk_improved2(A,C,D)
print(D)

[[0.72504188 0.61274687 0.18059746 0.39646311]
 [0.5083575  0.27832474 0.31340808 0.24692576]
 [1.24370779 1.23689945 1.07284237 0.84626008]
 [0.43410972 1.07099037 0.69538488 1.12568229]]


So, let's consider the function that multiplies banded matrices and stores the product by diagonals. First, let's consider a function that transforms a banded matrix (p,q) into the set of diagonals we wish for.  

In [21]:
def store_diagonals(A, tol, dim):
    p, q = checkBanded(A, tol, dim)
    C = np.zeros((dim, p+q+1))
    if (p==dim-1) and (q== dim-1):
        return A
    else: # we may store the diagonal first, then upper and lower, then the next upper, next lower, ...
        for i in range(0, dim):
            C[i, 0] = A[i,i]
        for i in range(0, dim-1):
            ## lower bandwidth
            for j in range(0, p):
                C[i, j+1] = A[i+1, i]
            ## upper bandwidths
            for j in range(0, q):
                C[i, j+p+1] = A[i, i+1]
        return C
                

In [22]:
A = randomMatrix(4)
print(A)
print(checkBanded(A, 0.001, 4))

[[0.41151226 0.88608436 0.79985796 0.69285804]
 [0.43378327 0.07144454 0.40800957 0.96427849]
 [0.74419914 0.15307497 0.71961756 0.93175154]
 [0.16676694 0.83752934 0.99527658 0.82462233]]
[3 3]


In [23]:
print(B)
B_diag = store_diagonals(B, 0.001, 4)
print(B_diag)

#### IT WORKS!!

[[0.74672253 0.19327604 0.         0.        ]
 [0.92976217 0.03843801 0.27365385 0.        ]
 [0.         0.31017291 0.10036968 0.04308792]
 [0.         0.         0.23248406 0.96050782]]
[[0.74672253 0.92976217 0.19327604]
 [0.03843801 0.31017291 0.27365385]
 [0.10036968 0.23248406 0.04308792]
 [0.96050782 0.         0.        ]]


In [24]:
A= bandedMatrix(4, 2, 1)
print(A)
A_diag = store_diagonals(A, 0.001, 4)
print(A_diag)

[[0.89272785 0.61560634 0.         0.        ]
 [0.50272339 0.74294976 0.27127728 0.        ]
 [0.01144827 0.66839153 0.27747178 0.42564452]
 [0.         0.22843359 0.78926128 0.53650407]]
[[0.89272785 0.50272339 0.50272339 0.61560634]
 [0.74294976 0.66839153 0.66839153 0.27127728]
 [0.27747178 0.78926128 0.78926128 0.42564452]
 [0.53650407 0.         0.         0.        ]]


In [25]:
C= bandedMatrix(6, 2, 1)
print(C)
C_diag = store_diagonals(C, 0.001, 4)
print(C_diag)

[[0.21299431 0.22840916 0.         0.         0.         0.        ]
 [0.37009261 0.39105908 0.55058164 0.         0.         0.        ]
 [0.61181174 0.73839459 0.62596713 0.16093252 0.         0.        ]
 [0.         0.04726385 0.65243259 0.70850026 0.89551585 0.        ]
 [0.         0.         0.41426653 0.13305974 0.90816501 0.86785176]
 [0.         0.         0.         0.68648426 0.49097453 0.83207562]]
[[0.21299431 0.37009261 0.37009261 0.22840916]
 [0.39105908 0.73839459 0.73839459 0.55058164]
 [0.62596713 0.65243259 0.65243259 0.16093252]
 [0.70850026 0.         0.         0.        ]]


Now we can create the function that actually multiplies two banded matrices and then saves the results in diagonals. In order to minimize operations we can try to multiply just the bands

In [26]:
def ijk_improved(A,B,C):
    for i in range(0,n):
        for j in range(0,n):
            C[i,j]= np.dot(A[i,:], B[:,j])+C[i,j]
    return C
 
## When a banded of dimension n is not banded we get parameters p,q = dim-1, dim-1

## Class 07/10/2022


### Sparse systems: recommenders

#### Problem 3. 

**(a)**

We may consider 3 vectors:
- data = (10, -2, 3, 9, ...)
    - set of numbers that are not 0, *val*
- indices = (0, 4, 0, ,1 ...)
    - columns where the numbers are, it has the same dimensions as data *col_ind*
- indptr = (0,2,5,8,...)
    - it is smaller, and tells us when to change rows
    
Now we can recover the matrix with quite smaller memory size usage. 

There is also the coordinate form, using a, i, j for the $a_{ij} \neq 0$. We may use this form for the project. 

In [27]:
#A = scipy.sparse.csr matrix((data, col_ind, ))

**(b)**




In [28]:
import numpy as np
import scipy.sparse 

def smatvec(a, ja, ia, x, y, n):
    for i in range(0,n):
        for j in range(ia[i], ia[i+1]):
            y[i] = y[i] + a[j]*x[ja[j]]
        return y

**(c)**

Collection of matrices, each matrix having the corresponding parameters. 
Matrix Market form for python. 

#### Problem 4. 

There are functions in scipy.sparse to solve the corresponding linear system, we may have to tell the function how the matrix is stored, there are other functions that work for specific matrix forms. 

In [30]:
import scipy.sparse as spsp
from scipy.sparse import csr_matrix

'''
    rows, cols, data =np.loadtxt("CurlCurl_0.mtx", skiprows = 83, unpack = True)
rows = rows- 1
A = spsp.coo_matrix((data, rows, cols), shape=(11083, 11083))

### per acabar

cscA = spsp.csc_matrix(A)
lu= spspla.splu(cscA)
#print
'''


'\n    rows, cols, data =np.loadtxt("CurlCurl_0.mtx", skiprows = 83, unpack = True)\nrows = rows- 1\nA = spsp.coo_matrix((data, rows, cols), shape=(11083, 11083))\n\n### per acabar\n\ncscA = spsp.csc_matrix(A)\nlu= spspla.splu(cscA)\n#print\n'

# Class 21 october 2022 

Given a banded matrix $A \in B(b_l, b_u)$,
$$
A = \begin{pmatrix}
a_{11} & \cdots & a_{1, b_u+1} & 0 & \cdots & 0 \\
\vdots & \cdots & \cdots & \cdots & \cdots & 0 \\
a_{b_l +1, 1} & \cdots & \cdots & \cdots & \cdots & 0 \\
0 & \cdots & \cdots & \cdots & \cdots & 0 \\
\vdots & \cdots & \cdots & \cdots & \cdots & \vdots \\
0 & \cdots & \cdots & \cdots & \cdots & a_{nn} 
\end{pmatrix}
$$

we want to know what happens with their factorization matrices $A= LU$, are they $L+ U \in B(b_l, b_u)$. We have that $LU$ factorization mantains the banded structure. For instance:
$$
A = \begin{pmatrix}
2 & -1 & 0 & 0 \\
4 & -1 & 3 & 0 \\
0 & -1 & -2 & 1 \\
0 & 0 & 3 & 4 
\end{pmatrix}= \underbrace{\begin{pmatrix}
1 & 0 & 0 & 0 \\
2 & 1 & 0 & 0 \\
0 & -1 & 1 & 0 \\
0 & 0 & 3 & 1 
\end{pmatrix}}_L \underbrace{\begin{pmatrix}
2 & -1 & 0 & 0 \\
0 & 1 & 3 & 0 \\
0 & 0 & 1 & 1 \\
0 & 0 & 0 & 1
\end{pmatrix}}_U
$$

Something similar happens with the PLU factorization:
$$
A=\underbrace{\begin{pmatrix}
0 & 0 & 0 & 1 \\
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 
\end{pmatrix}}_P \underbrace{\begin{pmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
1/2 & 1/2 & -1/2 & 1 
\end{pmatrix}}_L \underbrace{\begin{pmatrix}
4 & 3 & 0 & 0 \\
0 & -1 & 2 & 0 \\
0 & 0 & 3 & 4 \\
0 & 0 & 0 & 1/2
\end{pmatrix}}_U
$$

In the PLU factorization we have $L+U \in B($ full but sparese with $b_l$ elements , $b_l + b_u$)