# Practice 7: Iterative methods

We will focus on the simplest methods. It does not enter on the exam!!!

We start with the linear model $A x=b, A \in mathbb{R}^{n\times n}, b \in \mathbb{R}^n$. Splitting of $A$: $ A = M -K$. Then we have 
$$
Ax = b \iff Mx - Kx =b \iff x = M^{-1}( Kx - b)
$$
using the fixed point iteration we get $x^{(k+1)}= M^{-1}(K x^{(k)} - b) = R x^{(k)} + c$ iterative scheme. Here $R = M^{-1} K$ is the iterative matrix, and we have $c= M^{-1}b$. 

Consider a function $g(x) $ which has the property to contract $|g'(x) | < 1$, then the iterative method converges $x_k = g(x_{k-1})$. Then, given $x \in \mathbb{R}^n$, then $Ax= b \iff x = Rx +c$ R needs to be contractive $g(R) < 1$ note that $g(R) = max(\lambda)$ for $\lambda \in Spec(R)$.

Consider now $A = D - L - U$. 

## Exercise 1. 

**Write functions that perform one step of Jacobi, Gauss-Seidel and SOR(ω) methods. Com- pute the solution of the linear system defined by A**



In [1]:
import numpy as np

A = np.array([[4,-1, -1, 0], [-1,4, 0, -1],[-1, 0, 4, -1], [0, -1, -1, 4] ])
b = np.array([[1,2,0,1]])
tol = 1e-9


In [2]:
A

array([[ 4, -1, -1,  0],
       [-1,  4,  0, -1],
       [-1,  0,  4, -1],
       [ 0, -1, -1,  4]])

In [3]:
b

array([[1, 2, 0, 1]])

Let's consider the Jacobi step:
- We have $Ax = b$
- We split $A = M-K$, leading to $x_{k+1} = R x_k +c$, where $R = M^{-1}K, c=M^{-1}b$. In order to do so we write $A = D - L -U$, where $D$ is the diagonal of $A$, and $-L, -U$ are the strictly lower and upper parts of $A$. Then, consdier now the Jacobi method to find $M, K$:
    - **Jacobi**: $M=D$

In [4]:
D = np.diagflat(np.diag(A))
L = D - np.tril(A)
U = D - np.triu(A)

In [5]:
D

array([[4, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 4]])

In [6]:
L

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 1, 0]])

In [7]:
U

array([[0, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

### Ex2

We donnot need to create the matrix, we know which components of $x$ we have to sum, and we just have to multiply the diagonal element by 3, we do not compute the matrix!! Without creating the matrix we can compute it simply. 

The only method we know in order to operate with matrices of this dimension is iterative methods! 

