In [1]:
import numpy as np

In [2]:
m= 6
s_0 = np.full((m, 1), 1)
S = np.zeros((m,m))
np.fill_diagonal(S, s_0)
S

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [5]:
lambda_0 = np.zeros((m, 1))
for i in range(0, m):
    lambda_0[i] = i
#lambda_0 = np.full((m, 1), 3)
rs = np.zeros((m, 1))
for i in range(0, m):
        rs[i] = s_0[i]*lambda_0[i]
        
rss = s_0 * lambda_0

print(rs, rss)

[[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [5.]] [[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [5.]]


In [2]:
n=3

A=np.zeros((n,n))
m = 2*n
G = np.identity(n)
#C =np.zeros((1, 2), np.matrix)
#C[0, 0] = np.identity(n)
#C[0,1] = np.identity(n)
C = np.block([
    [np.identity(n), np.identity(n)]
])

d = np.full((1, m), -10)
g = np.random.normal(0,1, size= (n, 1))
x_0 = np.zeros((n,1))
s_0 = np.full((m, 1), 1)
lambda_0 = np.full((m,1), 1)

print(C)
print(g)

[[1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1.]]
[[ 0.33190277]
 [-0.09023093]
 [ 0.96876371]]


In [3]:
rl = np.full((n, 1), 1)
rc = np.full((m, 1), 1)
rs = np.full((m, 1), 1)
mu = 1

m= 2*n
S = np.zeros((m,m))
np.fill_diagonal(S, s_0)
Lam = np.zeros((m,m))
np.fill_diagonal(Lam, lambda_0)

MK= np.block([
    [ G, -C, np.zeros((n,m)) ],
    [-C.T , np.zeros((m,m)), np.identity(m)], 
    [np.zeros((m,n)), S, Lam]
])

print(MK)

F_z0 = np.block([
    [rl],
    [rc],
    [rs]
])
print(F_z0)

[[ 1.  0.  0. -1. -0. -0. -1. -0. -0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0. -0. -1. -0. -0. -1. -0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1. -0. -0. -1. -0. -0. -1.  0.  0.  0.  0.  0.  0.]
 [-1. -0. -0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [-0. -1. -0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [-0. -0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [-1. -0. -0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [-0. -1. -0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [-0. -0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  1.]]
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]

In [91]:
dz = np.linalg.solve(MK, F_z0)
print(dz)

[[ 0.33333333]
 [ 0.33333333]
 [ 0.33333333]
 [-0.33333333]
 [-0.33333333]
 [-0.33333333]
 [-0.33333333]
 [-0.33333333]
 [-0.33333333]
 [ 1.33333333]
 [ 1.33333333]
 [ 1.33333333]
 [ 1.33333333]
 [ 1.33333333]
 [ 1.33333333]]


In [92]:
dx = dz[0:n]
dlamb = dz[(n):(n+m)]
ds = dz[(n + m):(n+m+m)]
print(dx)
print(dlamb)
print(ds)

[[0.33333333]
 [0.33333333]
 [0.33333333]]
[[-0.33333333]
 [-0.33333333]
 [-0.33333333]
 [-0.33333333]
 [-0.33333333]
 [-0.33333333]]
[[1.33333333]
 [1.33333333]
 [1.33333333]
 [1.33333333]
 [1.33333333]
 [1.33333333]]


In [101]:
def Newton_step(lamb0, dlamb, s0, ds):
    '''
    This function computes alpha so that the step-size
    alpha*dz guarantees feasibility.
    It is used on the step-size correction substeps 
    of the algorithm.
    

    Parameters
    ----------
    lamb0 : inequality constraints initial conditions
    dlamb : lambda step
    s0 : C^T x - d for x_0 initial point
    ds : s step

    Returns
    -------
    alp : Newton step size, alpha

    '''
    alp = 1
    idx_lamb0 = np.array(np.where(dlamb< 0)[0])
    if idx_lamb0.size >0 :
        alp= min(alp, np.min(-lamb0[idx_lamb0] / dlamb[idx_lamb0]))
        
    idx_s0 = np.array(np.where(ds<0))
    if idx_s0.size> 0:
        alp= min(alp, np.min(-s0[idx_s0] / ds[idx_s0]))
     
    return alp

alpha = Newton_step(lambda_0, dlamb, s_0, ds)
print(alpha)

1


In [94]:
idx_lamb0 = np.array(np.where(dlamb< 0))
print(idx_lamb0)
print(idx_lamb0.size)

[[0 1 2 3 4 5]
 [0 0 0 0 0 0]]
12


In [95]:
np.where(dlamb< 0)
# com que tots són negatius els canvia tots per 0

(array([0, 1, 2, 3, 4, 5]), array([0, 0, 0, 0, 0, 0]))

In [145]:
dlamb

array([[-0.33333333],
       [-0.33333333],
       [-0.33333333],
       [-0.33333333],
       [-0.33333333],
       [-0.33333333]])

In [144]:
dlamb.any()>0

True

In [146]:
min(dlamb)

array([-0.33333333])

In [97]:
lambda_0

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [68]:
np.min(-lambda_0/dlamb)

2.9999999999999987

In [98]:
alp=1
#idx_lamb0 = np.array(np.where(dlamb< 0)[0])
min(alp, np.min(-lambda_0[idx_lamb0] / dlamb[idx_lamb0]))

1

In [99]:
print(idx_lamb0)
print(lambda_0)
#lambda_0[idx_lamb0]
print(idx_lamb0.shape)

for i in idx_lamb0:
    print(i)
    #print(lambda_0[i])
#min(lambda_0[idx_lamb0])
print(lambda_0[0])
print(lambda_0[1])

[[0 1 2 3 4 5]
 [0 0 0 0 0 0]]
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]]
(2, 6)
[0 1 2 3 4 5]
[0 0 0 0 0 0]
[1]
[1]


 El que fa Newton_step és agafar els steps de dlambda que siguin negatius, i llavors agafa com a valor d'alpha el mínim entre el valor que ja teníem com alpha i el mínim entre els quocients de lambda entre el valor de dlamb en positiu.

In [127]:
def compute_mus(s0, lamb0, n, dz, alp):
    m=2*n
    dx = dz[0:n]
    dlamb = dz[(n):(n+m)]
    ds = dz[(n + m):(n+m+m)]
    
    mu = np.dot(s0.T,lamb0) / m
    mu2 = np.dot((s0 + alp*ds).T,(lamb0 + alp*dlamb))/m
    sigma = (mu2/mu)**3
    
    return mu, mu2, sigma

In [128]:
mu, mu2, sigma = compute_mus(s_0, lambda_0, n, dz, alp)

In [129]:
np.dot(s_0.T, lambda_0)

array([[6]])

In [130]:
print(mu)
print(mu2)
print(sigma)

[[1.]]
[[1.55555556]]
[[3.76406036]]


In [131]:
def predictor_substep(n, G, C, x_0, lambda_0, s_0, rl, rc, rs):
    '''
    This function conducts the 1)Predictor substep: 
        it computes the standard Newton step dz=(dx, dlamb, ds)
        by solving the KKT system
    

    Returns
    -------
    dz: array 
        The solution of the KKT system, which accounts for the 
        Newton's step size

    '''
    
    m= 2*n
    S = np.zeros((m,m))
    np.fill_diagonal(S, s_0)
    Lam = np.zeros((m,m))
    np.fill_diagonal(Lam, lambda_0)
    
    MK= np.block([
        [ G, -C, np.zeros((n,m)) ],
        [-C.T , np.zeros((m,m)), np.identity(m)], 
        [np.zeros((m,n)), S, Lam]
    ])
    

    F_z0 = np.block([
        [rl],
        [rc],
        [rs]
    ])
    F_z0 = -F_z0
    ## Verify this step 
    dz = np.linalg.solve(MK, F_z0)
    
    return dz

In [138]:
e_vector=np.full((m, 1), 1)
DsDl_e = np.full((m, 1), ds*dlamb)
rs_new = - rs - DsDl_e + mu * sigma.T* e_vector
dz1 = predictor_substep(n, G, C, x_0, lambda_0, s_0, rl, rc, -rs_new)
print(dz1)

[[2.47233653]
 [2.47233653]
 [2.47233653]
 [1.73616827]
 [1.73616827]
 [1.73616827]
 [1.73616827]
 [1.73616827]
 [1.73616827]
 [1.47233653]
 [1.47233653]
 [1.47233653]
 [1.47233653]
 [1.47233653]
 [1.47233653]]


In [139]:
import numpy as np


def predictor_substep(n, G, C, x_0, lambda_0, s_0, rl, rc, rs):
    '''
    This function conducts the 1)Predictor substep: 
        it computes the standard Newton step dz=(dx, dlamb, ds)
        by solving the KKT system
    

    Returns
    -------
    dz: array 
        The solution of the KKT system, which accounts for the 
        Newton's step size

    '''
    
    m= 2*n
    S = np.zeros((m,m))
    np.fill_diagonal(S, s_0)
    Lam = np.zeros((m,m))
    np.fill_diagonal(Lam, lambda_0)
    
    MK= np.block([
        [ G, -C, np.zeros((n,m)) ],
        [-C.T , np.zeros((m,m)), np.identity(m)], 
        [np.zeros((m,n)), S, Lam]
    ])
    

    F_z0 = np.block([
        [rl],
        [rc],
        [rs]
    ])
    F_z0 = -F_z0
    ## Verify this step 
    dz = np.linalg.solve(MK, F_z0)
    
    return dz
  
  

def Newton_step(lamb0, dlamb, s0, ds):
    '''
    This function computes alpha so that the step-size
    alpha*dz guarantees feasibility.
    It is used on the step-size correction substeps 
    of the algorithm.
    

    Parameters
    ----------
    lamb0 : inequality constraints initial conditions
    dlamb : lambda step
    s0 : C^T x - d for x_0 initial point
    ds : s step

    Returns
    -------
    alp : Newton step size, alpha

    '''
    alp = 1
    idx_lamb0 = np.array(np.where(dlamb< 0))
    if idx_lamb0.size >0 :
        alp= min(alp, np.min(-lamb0[idx_lamb0] / dlamb[idx_lamb0]))
        
    idx_s0 = np.array(np.where(ds<0))
    if idx_s0.size> 0:
        alp= min(alp, np.min(-s0[idx_s0] / ds[idx_s0]))
     
    return alp

 
   
def compute_mus(s0, lamb0, n, dz, alp):
    '''
    This function computes the corresponding values
    on step 3 of the algorithm
    
    '''
    
    m=2*n
    dx = dz[0:n]
    dlamb = dz[(n):(n+m)]
    ds = dz[(n + m):(n+m+m)]
    
    mu = np.dot(s0.T,lamb0) / m
    mu2 = np.dot((s0 + alp*ds).T,(lamb0 + alp*dlamb))/m
    sigma = (mu2/mu)**3
    
    return mu, mu2, sigma



def testProblem(n):
    '''
    Here we may define the test problem (like the main function) to test our 
    algorithm.
    
    Parameters
    ----------
    n : dimension of the matrices and vectors we are defining

    Returns
    -------
    None.

    '''
    
    ####################
    ## INITIALIZATION ##
    ####################
    
    ## We initialize the test problem:
    A=np.zeros((n,n))
    m = 2*n
    G = np.identity(n)
    C = np.block([
        [np.identity(n), np.identity(n)]
    ])

    d = np.full((m, 1), -10)
    g = np.random.normal(0,1, size= (n, 1))
    x_0 = np.zeros((n, 1))
    s_0 = np.full((m, 1), 1)
    lambda_0 = np.full((m,1), 1)
    z0 = np.block([
        [x_0],
        [lambda_0],
        [s_0]
    ])
    
    
    ########################
    ## STOPPING CRITERION ##
    ########################
    
    epsilon = 1e-16
    maxIterations = 100
    rl_0 = np.full((n, 1), 1)
    rc_0 = np.full((m, 1), 1)
    rs_0 = np.full((m, 1), 1)
    mu_0= 1

    num_iteration = 0
    
    
    #########################################
    ## ITERATIVELLY APPLYING THE ALGORITHM ##
    #########################################
    
    #while abs(rl_0) > epsilon and abs(rc_0) > epsilon and abs(mu_0) > epsilon and num_iteration < maxIterations:
        
        ## 1) First we compute the predictor substep
    dz0 = predictor_substep(n, G, C, x_0, lambda_0, s_0, rl_0, rc_0, rs_0)
    dx = dz0[0:n]
    dlamb = dz0[(n+1):(n+m)]
    ds = dz0[(n + m + 1):(n+m+m)]
        ## 2) Step-size correction subestep:
    alp = Newton_step(lambda_0, dlamb, s_0, ds)
        ## 3) Computation of the mu's
    mu, mu2, sigma = compute_mus(s_0, lambda_0, n, dz0, alp)
        ## 4) Corrector substep 
    '''
        D_s D_lambda e gives a vector that has per coefficients
        the diagonal of D_s*D_lambda which correspond to ds*dlamb
        
        Therefore, there's no need to compute the whole matrix product,
        to optimize operations:
            
            #DS = np.zeros((m,m))
            #np.fill_diagonal(DS, ds)
            #Dlam = np.zeros((m,m))
            #np.fill_diagonal(Dlam, dlamb)
            #DS_lambda = np.zeros((m,m))
            #np.fill_diagonal(DS_lambda, ds*dlamb)
    '''
    
    e_vector=np.full((m, 1), 1)
    DsDl_e = np.full((m, 1), ds*dlamb)
    rs_new = - rs_0 - DsDl_e + mu * sigma* e_vector
    dz1 = predictor_substep(n, G, C, x_0, lambda_0, s_0, rl_0, rc_0, -rs_new)
        ## 5) Step-size correction substep
    dx1 = dz1[0:n]
    dlamb1 = dz1[(n+1):(n+m)]
    ds1 = dz1[(n + m + 1):(n+m+m)]
    alp1 = Newton_step(lambda_0, dlamb1, s_0, ds1)
        ## 6) Update substep:
    z1 = z0 + 0.95 * alp1 * dz1
    ## M_KKT gets updated by introducing the new values 
    # of s, lambda in the corresponding function
    
    print(z1)
    
    
testProblem(4)
    




ValueError: could not broadcast input array from shape (7,1) into shape (8,1)

In [134]:
rs.shape

(6, 1)

In [135]:
mu.shape

(1, 1)

## C4

In [7]:
import random
import numpy as np
import scipy

def randomMatrix(dim):
    A = np.zeros((dim,dim))
    for i in range(0, dim):
        for j in range(0,dim):
            A[i,j] = random.uniform(0,1)
    return A

In [8]:
A=randomMatrix(5)
print(A)

[[0.94450937 0.77791178 0.79801778 0.24891861 0.26439178]
 [0.77593072 0.61931269 0.27504412 0.94012468 0.98175059]
 [0.89173432 0.53835793 0.45918353 0.92142507 0.66047413]
 [0.76121949 0.83692238 0.91760196 0.49853494 0.06303305]
 [0.63742901 0.01463169 0.23643732 0.44962331 0.30209553]]


In [9]:
n=5
p=5
#A=np.zeros((n,p))
#m = 2*n
G = np.identity(n)
MK= np.block([
    [ G, -A ],
    [-A.T , np.zeros((p,p))]
])

print(np.linalg.eig(MK)[0])

[-2.63115877e+00  3.63115877e+00 -6.60058707e-01  1.66005871e+00
  1.00061312e+00  1.13590930e+00  1.07564028e+00 -1.35909302e-01
 -7.56402827e-02 -6.13124805e-04]


In [10]:
from scipy.linalg import ldl

lu, d, perm = ldl(A)
print(lu)
print(d)

[[ 1.          0.          0.          0.          0.        ]
 [ 0.82151723  1.          0.          0.          0.        ]
 [ 0.94412437  0.62740092  0.3592024  -0.46618452  1.        ]
 [ 0.80594171  0.23261476 -0.42391492  1.          0.        ]
 [ 0.67487844  0.          1.          0.          0.        ]]
[[ 0.94450937  0.          0.          0.          0.        ]
 [ 0.         -0.01812777 -0.50902723  0.          0.        ]
 [ 0.         -0.50902723 -0.12809157  0.          0.        ]
 [ 0.          0.          0.         -0.19135336  0.        ]
 [ 0.          0.          0.          0.         -0.08804253]]


In [11]:
print(perm)

[0 1 4 3 2]


In [12]:
print(lu[perm,:])

[[ 1.          0.          0.          0.          0.        ]
 [ 0.82151723  1.          0.          0.          0.        ]
 [ 0.67487844  0.          1.          0.          0.        ]
 [ 0.80594171  0.23261476 -0.42391492  1.          0.        ]
 [ 0.94412437  0.62740092  0.3592024  -0.46618452  1.        ]]


In [13]:
d

array([[ 0.94450937,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.01812777, -0.50902723,  0.        ,  0.        ],
       [ 0.        , -0.50902723, -0.12809157,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , -0.19135336,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        , -0.08804253]])

In [ ]:
## I want a function that recognizes when D is not diagonal

In [16]:
def isDiagonal(A, thres= 1e-10):
    for i in range(0, A.shape[0]):
        for j in range(0, A.shape[1]):
            if i != j:
                if abs(A[i,j]) < thres:
                    return False
    return True

In [17]:
isDiagonal(d)

False

In [19]:
## when this happens we have to go throught the matrix

diagonal_dim1 = np.matrix([1])

In [20]:
diagonal_dim1

matrix([[1]])

In [21]:
isDiagonal(diagonal_dim1)

True

In [35]:
len(perm)

4

In [36]:
P = np.identity(4)[perm,:]

In [37]:
P

array([[0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.]])

In [38]:
P.T

array([[0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.]])

In [39]:
np.matmul(P, lu)

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 1.51823682,  1.        ,  0.        ,  0.        ],
       [ 0.4828429 , -0.20080262,  1.        ,  0.        ],
       [ 0.76641498,  0.68492232, -0.12581875,  1.        ]])

In [40]:
np.matmul(lu, P.T)

array([[ 1.        ,  0.68492232, -0.12581875,  0.76641498],
       [ 0.        ,  1.        ,  0.        ,  1.51823682],
       [ 0.        , -0.20080262,  1.        ,  0.4828429 ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [30]:
np.matmul(P,P.T)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
lu

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 2.33890624,  1.        ,  0.        ,  0.        ],
       [ 1.20803237, -0.00852457,  0.75226073,  1.        ],
       [ 0.6884357 , -1.16279527,  1.        ,  0.        ]])

In [10]:
y = np.array([1,2,3,4])
print(y)
np.matmul(P, y)

[1 2 3 4]


array([1., 2., 3., 4.])

In [11]:
perm_check = [i for i in range(0, 4)]

In [12]:
perm_check

[0, 1, 2, 3]

In [13]:
perm_check == perm

array([ True, False, False,  True])

In [14]:
indicador = False
for i in range(0,4):
    if perm_check[i] != perm[i]:
        indicador = True
        
print(indicador)

True


In [7]:
LD = np.matmul(lu, d)

In [8]:
np.matmul(LD, lu.T)

array([[0.4127415 , 0.4036831 , 0.68216605, 0.39950753],
       [0.4036831 , 0.18235022, 0.4478133 , 0.23697663],
       [0.68216605, 0.4478133 , 0.3036944 , 0.13673111],
       [0.39950753, 0.23697663, 0.13673111, 0.49735838]])

In [37]:
LL = lu[perm,:]
LLD = np.matmul(LL, d)
np.matmul(LLD, LL.T)

array([[0.77247334, 0.93848786, 0.54906715, 0.66708095],
       [0.93848786, 0.37733788, 0.15684956, 0.74721752],
       [0.54906715, 0.15684956, 0.96815027, 0.03799141],
       [0.66708095, 0.74721752, 0.03799141, 0.5512904 ]])

In [40]:
y = np.array([1,2,3,4])
print(y.shape)

(4,)


In [43]:
np.diag(d).shape

(4,)

In [45]:
y/np.diag(d)

array([  1.29454305,  -2.62177091,   3.26394642, -21.24007359])

In [47]:
np.array[y]/np.array[[np.diag(d)]]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [50]:
[y]

[array([1, 2, 3, 4])]

In [44]:
print(d)
print(np.diag(d))

[[ 0.77247334  0.          0.          0.        ]
 [ 0.         -0.76284316  0.          0.        ]
 [ 0.          0.          0.91913274  0.        ]
 [ 0.          0.          0.         -0.18832326]]
[ 0.77247334 -0.76284316  0.91913274 -0.18832326]


In [20]:
from scipy.linalg import solve_triangular

SS = solve_triangular(LL, np.diag(d), lower=True, unit_diagonal=True)
print(SS)
print(SS.shape)

[ 0.91503693 -1.63863491  1.24807601 -0.62382978]
(4,)


In [17]:
A_chol = np.linalg.cholesky(A)
print(A_chol)

LinAlgError: Matrix is not positive definite

## C4 strategies

Strategy 1

In [22]:
import numpy as np
import time
import matplotlib.pyplot as plt
#import scipy
from scipy.linalg import ldl
from scipy.linalg import solve_triangular

def strategy1(n, G, C, x_0, lambda_0, s_0, rl, rc, rs):
     m= 2*n
     S = np.zeros((m,m))
     np.fill_diagonal(S, s_0)
     Lam = np.zeros((m,m))
     np.fill_diagonal(Lam, lambda_0)
     
     MK = np.block([
         [G, -C],
         [- C.T, - np.matmul(np.linalg.inv(Lam), S)]
         ])
     F_z0 = np.block([
         [rl],
         [rc - np.matmul(np.linalg.inv(Lam), rs)]
         ])
     F_z0 = -F_z0
     
     ## LDL^T factorization:
     lu, d, perm = ldl(MK)
     L_triag = lu[perm, :]
     '''
         This is equivalent to multiplicate the lu by the permutation matrix P
         Note that the matrix lu[perm, :] = P.dot(lu) is the triangular matrix we are looking for 
         where P = I[perm,:]
     '''
     
     ## We solve now two triangular systems and a diagonal direct system
     dy1 = solve_triangular(L_triag, F_z0[perm], lower=True, unit_diagonal=True)
     dy2 = dy1/np.diag(d)
     dy3 = solve_triangular(L_triag.T, dy2[perm], lower=False, unit_diagonal=True)
     
     
        
     ## Now we compute dz1 as the function output
     Lam1 = np.zeros((m,m))
     np.fill_diagonal(Lam1, 1/lambda_0)
     ds = np.matmul(Lam1, -rs- np.matmul(S, dy3[n: (n+m)]))
     
     dz = np.block([
         [dy3],
         [ds]
     ])
     
     return dz

In [25]:
## We initialize the test problem:
n=2

A=np.zeros((n,n))
m = 2*n
G = np.identity(n)
C = np.block([
    [np.identity(n), np.identity(n)]
])

d = np.full((m, 1), -10)
g = np.random.normal(0,1, size= (n, 1))
x_0 = np.zeros((n, 1))
s_0 = np.full((m, 1), 1)
lambda_0 = np.full((m,1), 1)
z0 = np.block([
    [x_0],
    [lambda_0],
    [s_0]
])

In [27]:
print(C)
print(z0)

[[1. 0. 1. 0.]
 [0. 1. 0. 1.]]
[[0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [28]:
rl_0 = np.full((n, 1), 1)
rc_0 = np.full((m, 1), 1)
rs_0 = np.full((m, 1), 1)

dz0 = strategy1(n, G, C, x_0, lambda_0, s_0, rl_0, rc_0, rs_0)

In [29]:
dz0.shape

(10, 6)

In [30]:
dz0

array([[-2.25      , -2.25      ,  1.125     ,  1.125     ,  1.5       ,
         1.5       ],
       [-2.25      , -2.25      ,  1.125     ,  1.125     ,  1.5       ,
         1.5       ],
       [-0.75      , -0.75      ,  0.375     ,  0.375     ,  0.5       ,
         0.5       ],
       [-0.75      , -0.75      ,  0.375     ,  0.375     ,  0.5       ,
         0.5       ],
       [-0.5       , -0.5       ,  0.25      ,  0.25      ,  0.33333333,
         0.33333333],
       [-0.5       , -0.5       ,  0.25      ,  0.25      ,  0.33333333,
         0.33333333],
       [-0.25      , -0.25      , -1.375     , -1.375     , -1.5       ,
        -1.5       ],
       [-0.25      , -0.25      , -1.375     , -1.375     , -1.5       ,
        -1.5       ],
       [-0.5       , -0.5       , -1.25      , -1.25      , -1.33333333,
        -1.33333333],
       [-0.5       , -0.5       , -1.25      , -1.25      , -1.33333333,
        -1.33333333]])

In [51]:
1/np.sqrt(2)

0.7071067811865475