In [2]:
"""
Effect of GE and GEPP on a banded matrix
"""

import numpy as np
import scipy.linalg as spla

def isbanded(A,ubw,lbw,tol):
    for i in range(0,n):
        for j in range(0,max(-lbw+i,0)):
            if abs(A[i,j])>tol: 
               return 0
        for j in range(min(i+ubw+1,n),n):
            if abs(A[i,j])>tol: 
               return 0
    return 1

def lunopiv(A,n,ptol):
    for k in range(0,n-1):
        pivot = A[k,k]
        if abs(pivot) < ptol:
           print("zero pivot encountered")
           break
        for i in range(k+1,n):
            A[i,k] = A[i,k]/pivot
            for j in range(k+1,n):
                A[i,j] = A[i,j] - A[i,k]*A[k,j]
    L = np.eye(n)+np.tril(A,-1)
    U = np.triu(A)
    return L,U


"""
MAIN
"""

n=6; ubw=3; lbw=1; 

A=np.zeros((n,n))
for i in range (0,n):
    for j in range(max(-lbw+i,0),min(i+ubw+1,n)):
        A[i,j]=np.random.rand()  #generates random number uniformly in [0,1]

print(A); print("\n");
AA=np.copy(A)

Lnp,Unp=lunopiv(A,n,1.e-16)
print("GE (LU):", isbanded(Lnp,ubw,lbw,1.e-15), isbanded(Unp,ubw,lbw,1.e-15))

P,L,U = spla.lu(AA)
print("GEPP (LU):", isbanded(L,ubw,lbw,1.e-15), isbanded(U,ubw,lbw,1.e-15))



LpU=L+U
print(LpU)
for ubw in range(0,n):
    for lbw in range(0,n):
        print(ubw,lbw,isbanded(LpU,ubw,lbw,1.e-15))

for ubw in range(0,n):
    lbw=0;
    while (isbanded(LpU,ubw,lbw,1.e-15)!=1 and lbw<n):
        lbw=lbw+1;
    if lbw<n:
        print("banda GEPP(L+U): ubw=%d lbw=%d\n"%(ubw,lbw))
       #quit() 
        break



[[0.53713281 0.5404301  0.09616644 0.87051634 0.         0.        ]
 [0.87464428 0.95114803 0.81361964 0.52939568 0.20255443 0.        ]
 [0.         0.7314098  0.22303381 0.51045671 0.41537799 0.03811765]
 [0.         0.         0.67425378 0.40471896 0.91992855 0.4914963 ]
 [0.         0.         0.         0.51191222 0.96088747 0.15217362]
 [0.         0.         0.         0.         0.86276756 0.98029597]]


GE (LU): 1 1
GEPP (LU): 0 0
[[ 1.87464428  0.95114803  0.81361964  0.52939568  0.20255443  0.        ]
 [ 0.          1.7314098   0.22303381  0.51045671  0.41537799  0.03811765]
 [ 0.          0.          1.67425378  0.40471896  0.91992855  0.4914963 ]
 [ 0.61411573 -0.05972693 -0.57866794  1.81009203  0.43275055  0.2866898 ]
 [ 0.          0.          0.          0.          1.86276756  0.98029597]
 [ 0.          0.          0.          0.63191859  0.79676658  0.18994194]]
0 0 0
0 1 0
0 2 0
0 3 0
0 4 0
0 5 0
1 0 0
1 1 0
1 2 0
1 3 0
1 4 0
1 5 0
2 0 0
2 1 0
2 2 0
2 3 0
2 4 0
2 

In [3]:
"""
Effect of GE and GEPP on a banded matrix
"""

import numpy as np
import scipy.linalg as spla

def isbanded(A,ubw,lbw,tol):
    for i in range(0,n):
        for j in range(0,max(-lbw+i,0)):
            if abs(A[i,j])>tol: 
               return 0
        for j in range(min(i+ubw+1,n),n):
            if abs(A[i,j])>tol: 
               return 0
    return 1


"""
MAIN
"""

n=10 
nsys=100
outfile = open("banded_LU_varis.out","w")

for ubwini in range (0,n):
    for lbwini in range (0,n):
        ubwmax=0; lbwmax=0
        for isys in range (0,nsys):
            ubw=ubwini; lbw=lbwini
            A=np.zeros((n,n))
            for i in range (0,n):
                for j in range(max(-lbw+i,0),min(i+ubw+1,n)):
                    A[i,j]=np.random.rand()  #generates random number uniformly in [0,1]
 
            if (isbanded(A,ubw,lbw,1.e-15)!=1):
               print('NO!!'); quit()

            P,L,U = spla.lu(A)
            LpU=L+U
            band=0; ubw=0;
            while (ubw<n and band==0):
                lbw=0
                while (lbw<n and band==0):
                    if (isbanded(LpU,ubw,lbw,1.e-15)==1): 
                       band=1 
                    lbw=lbw+1
                ubw=ubw+1
            ubw=ubw-1
            lbw=lbw-1
            if ubw>ubwmax:
               ubwmax=ubw
            if lbw>lbwmax:
               lbwmax=lbw
        outfile.write('%d %d %d %d\n' % (ubwini,lbwini,ubwmax,lbwmax))


In [4]:
"""
Banded matrices by diagonals, multiplication of matrices
"""

import numpy as np
import scipy.sparse

def isbanded(A,ubw,lbw,tol):
    for i in range(0,n):
        for j in range(0,max(-lbw+i,0)):
            if abs(A[i,j])>tol: 
               return 0
        for j in range(min(i+ubw+1,n),n):
            if abs(A[i,j])>tol: 
               return 0
    return 1

def band_storage(qA,A):
    Ab=np.zeros((n,n))
    for i in range (0,n):
        for j in range (0,n):
            if (qA+i-j<n):
                Ab[qA+i-j,j]=A[i,j]
    return Ab

def banded_mult(pA,qA,Ab,pB,qB,Bb):
    Cb=np.zeros((n,n))
    nvecA=pA+qA+1; nvecB=pB+qB+1  
    qC=min(qA+qB,n)
    pC=min(pA+pB,n)
    for i in range (0,n):
        for j in range (0,n):
            for k in range (0,n):
                if(qA+i-k<n and qB+k-j<n and qC+i-j<n):
                   Cb[qC+i-j,j]=Cb[qC+i-j,j]+Ab[qA+i-k,k]*Bb[qB+k-j,j]
    return qC,pC,Cb
    
     
      

"""
MAIN
"""

n=6; 
pA=1; qA=1;
pB=1; qB=2;

A=np.zeros((n,n))
for i in range (0,n):
    for j in range(max(-pA+i,0),min(i+qA+1,n)):
        A[i,j]=np.random.rand()  #generates random number uniformly in [0,1]

if (isbanded(A,qA,pA,1.e-15)!=1):
   print('No A\n'); quit();


B=np.zeros((n,n))
for i in range (0,n):
    for j in range(max(-pB+i,0),min(i+qB+1,n)):
        B[i,j]=np.random.rand()  #generates random number uniformly in [0,1]

if (isbanded(B,qB,pB,1.e-15)!=1):
   print('No B\n'); quit();



#Band storage example
nvecA=pA+qA+1; nvecB=pB+qB+1   #number of vectors to store A (resp B)

Ab=band_storage(qA,A)
Bb=band_storage(qB,B);

print(A)
print('\n')
print(Ab[0:nvecA,:])
print('\n')
Abs=scipy.sparse.dia_matrix(A)
print(Abs)



print('\n')
print(B)
print('\n')
print(Bb[0:nvecB,:])
print('\n')
Bbs=scipy.sparse.dia_matrix(B)
print(Bbs)


#Band storage multiplication
pC,qC,Cb=banded_mult(pA,qA,Ab,pB,qB,Bb)

print('\n')
print('Product C=AB');
print(Cb)

"""
Using scipy.sparse.dia_matrix structure: do computations matrix x vector in csr format (or coo format)
""" 

print('\n')
print(np.dot(A,B))
print('\n')
print((Abs.tocsr().dot(Bbs.tocsr())).todia())
print('\n')
print(Abs.dot(Bbs).todia())



"""
Comments:

  There are functions for banded/diagonal storage  
        e.g. scipy.linalg.cholesky_banded
             see https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.linalg.cholesky_banded.html

"""

[[0.09296658 0.6000218  0.         0.         0.         0.        ]
 [0.53452372 0.58161351 0.99657576 0.         0.         0.        ]
 [0.         0.0523886  0.03974513 0.04650533 0.         0.        ]
 [0.         0.         0.63547855 0.5735155  0.33535057 0.        ]
 [0.         0.         0.         0.72009302 0.70266697 0.45700375]
 [0.         0.         0.         0.         0.32038922 0.61517874]]


[[0.         0.6000218  0.99657576 0.04650533 0.33535057 0.45700375]
 [0.09296658 0.58161351 0.03974513 0.5735155  0.70266697 0.61517874]
 [0.53452372 0.0523886  0.63547855 0.72009302 0.32038922 0.        ]]


  (1, 0)	0.5345237232961966
  (2, 1)	0.052388602399135675
  (3, 2)	0.6354785502352568
  (4, 3)	0.7200930153059536
  (5, 4)	0.3203892237100696
  (0, 0)	0.09296658383674017
  (1, 1)	0.58161350632615
  (2, 2)	0.03974512794779672
  (3, 3)	0.5735154986719052
  (4, 4)	0.7026669661147937
  (5, 5)	0.6151787378598937
  (0, 1)	0.600021802201576
  (1, 2)	0.9965757564931061
  (2, 3)

'\nComments:\n\n  There are functions for banded/diagonal storage  \n        e.g. scipy.linalg.cholesky_banded\n             see https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.linalg.cholesky_banded.html\n\n'

In [5]:
import numpy as np
import scipy.sparse as spsp
#import scipy.sparse.linalg as spspla
from scipy.sparse import csc_matrix, linalg as spspla
#import matplotlib.pyplot as plt

rows,cols,data=np.loadtxt("CurlCurl_0.mtx",skiprows=83,unpack=True)
rows=rows-1; cols=cols-1;
A=spsp.coo_matrix((data,(rows,cols)),shape=(11083,11083))

#plt.spy(A)
#plt.show()

cscA = spsp.csc_matrix(A)
lu=spspla.splu(cscA)
print(lu.perm_r)
print(lu.perm_c)

FileNotFoundError: CurlCurl_0.mtx not found.

In [6]:
"""
Sparse matrix CSR: saxpy
"""


import numpy as np
import scipy.sparse


def smatvec(a,ja,ia,x,y,n): #computes A*x+y
    for i in range (0,n):
        for j in range (ia[i],ia[i+1]):
            y[i]=y[i]+a[j]*x[ja[j]]
    return y




data    = np.array([10,-2,3,9,3,7,8,7,3,8,7,5,8,9,9,13,4,2,-1])   #val
indices = np.array([ 0, 4,0,1,5,1,2,3,0,2,3,4,1,3,4, 5,1,4, 5])   #col_ind
indptr  = np.array([ 0, 2,5,8,12,16,19])                          #row_ptr


#Important:
# Instead of n^2 elements, 
# we save only 2 #nnz + n + 1, where nnz=set of non-zero elements of A

n=6;
A = scipy.sparse.csr_matrix((data,indices,indptr),shape=(n,n))
print(A.todense())

x=np.ones(n)
y=np.zeros(n) 
yy=np.ones(n) 

print(smatvec(data,indices,indptr,x,y,n))
print(smatvec(data,indices,indptr,x,yy,n))


[[10  0  0  0 -2  0]
 [ 3  9  0  0  0  3]
 [ 0  7  8  7  0  0]
 [ 3  0  8  7  5  0]
 [ 0  8  0  9  9 13]
 [ 0  4  0  0  2 -1]]
[ 8. 15. 22. 23. 39.  5.]
[ 9. 16. 23. 24. 40.  6.]


In [7]:
"""
Sparse matrix CSR: saxpy transpose A
"""


import numpy as np
import scipy.sparse


def smatvec(a,ja,ia,x,y,n): #computes A*x+y
    for i in range (0,n):
        for j in range (ia[i],ia[i+1]):
            y[i]=y[i]+a[j]*x[ja[j]]
    return y

def transmatvec(a,ja,ia,x,n): #Computes A^t *x
    y=np.zeros(n)
    for i in range (0,n):
        for j in range (ia[i],ia[i+1]):
            y[ja[j]]=y[ja[j]]+a[j]*x[i]
    return y
        

data    = np.array([10,-2,3,9,3,7,8,7,3,8,7,5,8,9,9,13,4,2,-1])   #val
indices = np.array([ 0, 4,0,1,5,1,2,3,0,2,3,4,1,3,4, 5,1,4, 5])   #col_ind
indptr  = np.array([ 0, 2,5,8,12,16,19])                          #row_ptr


#Important:
# Instead of n^2 elements, 
# we save only 2 #nnz + n + 1, where nnz=set of non-zero elements of A

n=6;
A = scipy.sparse.csr_matrix((data,indices,indptr),shape=(n,n))
x=np.ones(n)
y=np.zeros(n) 
yy=np.ones(n) 

print("A:")
print(A.todense())

print("\n")
print("x:")
print(x)
print("y:")
print(y)
print("yy:")
print(yy)

print("\n")
print("A*x:")
print(smatvec(data,indices,indptr,x,y,n))
print("check:")
print(A.dot(x))
print("A*x+yy:")
print(smatvec(data,indices,indptr,x,yy,n))


print("\n")
print("A^t *x:")
print(transmatvec(data,indices,indptr,x,n))
print("check:")
print((A.T).dot(x))
print("\n")

A:
[[10  0  0  0 -2  0]
 [ 3  9  0  0  0  3]
 [ 0  7  8  7  0  0]
 [ 3  0  8  7  5  0]
 [ 0  8  0  9  9 13]
 [ 0  4  0  0  2 -1]]


x:
[1. 1. 1. 1. 1. 1.]
y:
[0. 0. 0. 0. 0. 0.]
yy:
[1. 1. 1. 1. 1. 1.]


A*x:
[ 8. 15. 22. 23. 39.  5.]
check:
[ 8. 15. 22. 23. 39.  5.]
A*x+yy:
[ 9. 16. 23. 24. 40.  6.]


A^t *x:
[16. 28. 16. 23. 14. 15.]
check:
[16. 28. 16. 23. 14. 15.]


